services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - NAME=MahaLigat  
  
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/db:/app/db
    environment:
      - NAME=MahaLigat
    

  
   

